import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Revalidate } from "next/dist/server/lib/revalidate";
import { AppConfigDynamic } from "next/dist/build/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Crypto Tracker",
  description: "Generated by create next app",
};
// Sets the rendering behavior of the page to be dynamic for every request.
// 'force-dynamic' ensures that the page is always rendered on the server side initially
export const dynamic: AppConfigDynamic = "force-dynamic";
// Prevents caching of the page
export const revalidate: Revalidate = 0;

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
