import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.scss";
import { Revalidate } from "next/dist/server/lib/revalidate";
import { AppConfigDynamic } from "next/dist/build/utils";
import Navbar from "@/components/Navbar/Navbar";
import { StoreProvider } from "@/lib/store/storeProvider";
import { AppInitializer } from "./appInitializer";
import { cookies } from "next/headers";
import { fetchInitialDataBasedOnRoute } from "@/utils/api.utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Crypto Tracker",
  description: "Generated by create next app",
};
// Sets the rendering behavior of the page to be dynamic for every request.
// 'force-dynamic' ensures that the page is always rendered on the server side initially
export const dynamic: AppConfigDynamic = "force-dynamic";
// Prevents caching of the page
export const revalidate: Revalidate = 0;

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  if (typeof window !== "undefined") {
    console.log("App.js rendered in Browser,", children);
  }

  // Access cookies in server components
  const cookieStore = cookies();

  // Fetch initial data based on the route and cookie information
  const initialData = await fetchInitialDataBasedOnRoute(cookieStore);

  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider initialData={initialData}>
          <AppInitializer />
          <Navbar />
          {children}
        </StoreProvider>
      </body>
    </html>
  );
}
